//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunCat.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RunCat.Languages.language", typeof(language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Runcat_Exit {
            get {
                return ResourceManager.GetString("Runcat_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runcat_Language.
        /// </summary>
        internal static string Runcat_Language {
            get {
                return ResourceManager.GetString("Runcat_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runner.
        /// </summary>
        internal static string Runcat_Runner {
            get {
                return ResourceManager.GetString("Runcat_Runner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cat.
        /// </summary>
        internal static string Runcat_Runner_Cat {
            get {
                return ResourceManager.GetString("Runcat_Runner_Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horse.
        /// </summary>
        internal static string Runcat_Runner_Horse {
            get {
                return ResourceManager.GetString("Runcat_Runner_Horse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parrot.
        /// </summary>
        internal static string Runcat_Runner_Parrot {
            get {
                return ResourceManager.GetString("Runcat_Runner_Parrot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runner Speed Limit.
        /// </summary>
        internal static string Runcat_Runner_Speed_Limit {
            get {
                return ResourceManager.GetString("Runcat_Runner_Speed_Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Runcat_Runner_Speed_Limit_Default {
            get {
                return ResourceManager.GetString("Runcat_Runner_Speed_Limit_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup.
        /// </summary>
        internal static string Runcat_Startup {
            get {
                return ResourceManager.GetString("Runcat_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Runcat_Theme {
            get {
                return ResourceManager.GetString("Runcat_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Runcat_Theme_Dark {
            get {
                return ResourceManager.GetString("Runcat_Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Runcat_Theme_Default {
            get {
                return ResourceManager.GetString("Runcat_Theme_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Runcat_Theme_Light {
            get {
                return ResourceManager.GetString("Runcat_Theme_Light", resourceCulture);
            }
        }
    }
}
